// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcqmpvfgepruwgxzfjzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjcW1wdmZnZXBydXdneHpmanp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NTc5MDgsImV4cCI6MjA2MjMzMzkwOH0.avZUr0--1hm-jrvApfy5LDsZhUgjGIpYaiSEGhuir-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);